version: "3"

services:
  elasticsearch:
    build: ./elasticsearch
    environment:
      - "discovery.type=single-node"
    ports:
      - "9200:9200"
    networks:
      - web
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data

  server:
    build: ./server
    restart: always
    ports:
      - "5000:5000"
    networks:
      - web
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"

  client:
    build: ./client
    ports:
      - "8080:8080"
    networks:
      - web
    depends_on:
      - server

networks:
  web: